name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: npm ci && npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::824246083439:role/Rebays-Website-S3-Deploy-Role
          aws-region: ap-southeast-2

      - name: List S3 Bucket Contents
        run: aws s3 ls s3://rebays-website