name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: npm ci && npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::824246083439:role/Rebays-Website-S3-Deploy-Role
          aws-region: ap-southeast-2

      - name: Deploy to S3
        run: aws s3 sync ./out s3://rebays-website --delete